---

version: "v-{build}"

branches:
  only:
    - master

# skip_non_tags: true

image: Visual Studio 2019

configuration:
- Release

clone_folder: C:\projects\datalevin

environment:
  GRAALVM_HOME: C:\projects\datalevin\graalvm\graalvm-ce-java11-22.3.0
  DTVL_NATIVE_EXTRACT_DIR: C:\projects\datalevin

clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }

build_script:
- cmd: >-
    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat', 'lein.bat')"

    call lein.bat self-install

- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

    powershell -Command "if (Test-Path('graalvm')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java11-windows-amd64-22.3.0.zip', 'graalvm.zip') }"

    powershell -Command "if (Test-Path('graalvm')) { return } else { Expand-Archive graalvm.zip graalvm }"

    cd native

    call script\compile.bat

    7z a dtlv-%APPVEYOR_REPO_TAG_NAME%-windows-amd64.zip dtlv.exe

# artifacts:
#   - path: native\dtlv-$(APPVEYOR_REPO_TAG_NAME)-windows-amd64.zip

# deploy:
#   provider: GitHub
#   auth_token:
#     secure: QIiuupmpAl2Y5kxVyFJTSDRIj/uKyXXE3PzARE//JY44zXEJ7vbqvhcftKq/dFdf
#   artifact: /.*\.zip/
#   force_update: true
#   on:
#     APPVEYOR_REPO_TAG: true
